.TH ABDUCO 1 abduco\-VERSION
.nh
.SH NAME
abduco - terminal session manager
.SH SYNOPSIS
.B abduco
.RB [ \-e
.IR detachkey ]
.RB [ \-r ]
.RB [ \-f ]
.RB \-c
.RB name
.RB command
.RI [ args \ ... "" ]
.br
.B abduco
.RB [ \-e
.IR detachkey ]
.RB [ \-r ]
.RB [ \-f ]
.RB \-n
.RB name
.RB command
.RI [ args \ ... "" ]
.br
.B abduco
.RB [ \-e
.IR detachkey ]
.RB [ \-r ]
.RB [ \-f ]
.RB [ \-l ]
.RB \-A
.RB name
.RB command
.RI [ args \ ... "" ]
.br
.B abduco
.RB [ \-e
.IR detachkey ]
.RB [ \-r ]
.RB [ \-l ]
.RB \-a
.RB name
.br
.SH DESCRIPTION
.B abduco
provides a way to disconnect a given application from its controlling
terminal, thus it provides roughly the same session attach/detach support as
.BR screen(1) , " tmux(1)" " or" " dtach(1)".

If the
.BR command
to execute is not specified, the environment variable
.BR $ABDUCO_CMD
is examined, if it is not set
.BR dvtm(1)
is executed.

All session related information is stored in the following directories (first
to succeed is used):
.RS
.nf
.PP
.B $ABDUCO_SOCKET_DIR/abduco
.B $HOME/.abduco
.B $TMPDIR/abduco/$USER
.B /tmp/abduco/$USER
.fi
.RE

However if a given session name represents either a relative or absolute path
it is used unmodified.

If for some reason the
.BR unix(7)
domain socket representing a session is deleted, sending
.BR SIGUSR1
to the server process will recreate it.
.SH OPTIONS
If no command line arguments are given all currently active sessions are
printed sorted by their respective creation date. Lines starting with an
asterik
.BR *
indicate that at least one client is connected.
A plus sign
.BR +
indicates that the command terminated while no client was connected, attach
to get its exit status.
.TP
.B \-v
Print version information to standard output and exit.
.TP
.B \-r
Readonly session, i.e. user input is ignored.
.TP
.B \-e \fIdetachkey\fR
Set the key to detach which by default is set to CTRL+\\ i.e. ^\\ to detachkey.
.TP
.BI \-f
Force creation of session when there is an already terminated session of the same name,
after showing its exit status.
.TP
.BI \-c
Create a new session and attach immediately to it.
.TP
.BI \-n
Create a new session but do not attach to it.
.TP
.BI \-A
Try to connect to an existing session, upon failure create said session and attach immediately to it.
.TP
.BI \-a
Attach to an existing session.
.TP
.BI \-l
Attach with the lowest priority, meaning this client will be the last to control the size.
.SH EXAMPLE
Start a new session (assuming
.BR dvtm(1)
is in
.BR $PATH )
with
.nf

.B abduco -c my-session

.fi
do some work, then detach by pressing
.B CTRL+\e
and later reattach with
.nf

.B abduco -a my-session

.fi
.SH AUTHOR
abduco is written by Marc André Tanner <mat at brain-dump.org>
